// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class ELet  extends Exp {
  public final MatchPattern matchpattern_;
  public final Exp exp_1, exp_2;
  public ELet(MatchPattern p1, Exp p2, Exp p3) { matchpattern_ = p1; exp_1 = p2; exp_2 = p3; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.ELet) {
      eyg.Absyn.ELet x = (eyg.Absyn.ELet)o;
      return this.matchpattern_.equals(x.matchpattern_) && this.exp_1.equals(x.exp_1) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.matchpattern_.hashCode())+this.exp_1.hashCode())+this.exp_2.hashCode();
  }


}
