// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class EList  extends Exp {
  public final ListListItem listlistitem_;
  public EList(ListListItem p1) { listlistitem_ = p1; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.EList) {
      eyg.Absyn.EList x = (eyg.Absyn.EList)o;
      return this.listlistitem_.equals(x.listlistitem_);
    }
    return false;
  }

  public int hashCode() {
    return this.listlistitem_.hashCode();
  }


}
