// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class ENamedReference  extends Exp {
  public final String namedreference_;
  public ENamedReference(String p1) { namedreference_ = p1; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.ENamedReference) {
      eyg.Absyn.ENamedReference x = (eyg.Absyn.ENamedReference)o;
      return this.namedreference_.equals(x.namedreference_);
    }
    return false;
  }

  public int hashCode() {
    return this.namedreference_.hashCode();
  }


}
