// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class ENegInt  extends Exp {
  public final Integer integer_;
  public ENegInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.ENegInt) {
      eyg.Absyn.ENegInt x = (eyg.Absyn.ENegInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
