// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class EPerform  extends Exp {
  public final Exp exp_;
  public EPerform(Exp p1) { exp_ = p1; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.EPerform) {
      eyg.Absyn.EPerform x = (eyg.Absyn.EPerform)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
