// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class ERecord  extends Exp {
  public final ListRecordField listrecordfield_;
  public ERecord(ListRecordField p1) { listrecordfield_ = p1; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.ERecord) {
      eyg.Absyn.ERecord x = (eyg.Absyn.ERecord)o;
      return this.listrecordfield_.equals(x.listrecordfield_);
    }
    return false;
  }

  public int hashCode() {
    return this.listrecordfield_.hashCode();
  }


}
