// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class ETagged  extends Exp {
  public final String tag_;
  public final Exp exp_;
  public ETagged(String p1, Exp p2) { tag_ = p1; exp_ = p2; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.ETagged) {
      eyg.Absyn.ETagged x = (eyg.Absyn.ETagged)o;
      return this.tag_.equals(x.tag_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.tag_.hashCode())+this.exp_.hashCode();
  }


}
