// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class EVar  extends Exp {
  public final String id_;
  public EVar(String p1) { id_ = p1; }

  public <R,A> R accept(eyg.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.EVar) {
      eyg.Absyn.EVar x = (eyg.Absyn.EVar)o;
      return this.id_.equals(x.id_);
    }
    return false;
  }

  public int hashCode() {
    return this.id_.hashCode();
  }


}
