// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(eyg.Absyn.ELet p, A arg);
    public R visit(eyg.Absyn.EList p, A arg);
    public R visit(eyg.Absyn.ERecord p, A arg);
    public R visit(eyg.Absyn.ETagged p, A arg);
    public R visit(eyg.Absyn.ELambda p, A arg);
    public R visit(eyg.Absyn.EPerform p, A arg);
    public R visit(eyg.Absyn.EHandle p, A arg);
    public R visit(eyg.Absyn.EMatch p, A arg);
    public R visit(eyg.Absyn.EApply p, A arg);
    public R visit(eyg.Absyn.ESelect p, A arg);
    public R visit(eyg.Absyn.EVar p, A arg);
    public R visit(eyg.Absyn.EInt p, A arg);
    public R visit(eyg.Absyn.ENegInt p, A arg);
    public R visit(eyg.Absyn.EString p, A arg);
    public R visit(eyg.Absyn.ENamedReference p, A arg);

  }

}
