// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public abstract class ListItem implements java.io.Serializable {
  public abstract <R,A> R accept(ListItem.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(eyg.Absyn.LIExpr p, A arg);
    public R visit(eyg.Absyn.LISpread p, A arg);

  }

}
