// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public abstract class MatchPattern implements java.io.Serializable {
  public abstract <R,A> R accept(MatchPattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(eyg.Absyn.MPTagged p, A arg);
    public R visit(eyg.Absyn.MPRecord p, A arg);
    public R visit(eyg.Absyn.MPId p, A arg);

  }

}
