// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class MatchItem0  extends MatchItem {
  public final MatchPattern matchpattern_;
  public final Exp exp_;
  public MatchItem0(MatchPattern p1, Exp p2) { matchpattern_ = p1; exp_ = p2; }

  public <R,A> R accept(eyg.Absyn.MatchItem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.MatchItem0) {
      eyg.Absyn.MatchItem0 x = (eyg.Absyn.MatchItem0)o;
      return this.matchpattern_.equals(x.matchpattern_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.matchpattern_.hashCode())+this.exp_.hashCode();
  }


}
