// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public abstract class Param implements java.io.Serializable {
  public abstract <R,A> R accept(Param.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(eyg.Absyn.PId p, A arg);

  }

}
