// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class PExps  extends Program {
  public final Exp exp_;
  public PExps(Exp p1) { exp_ = p1; }

  public <R,A> R accept(eyg.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.PExps) {
      eyg.Absyn.PExps x = (eyg.Absyn.PExps)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
