// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public class PId  extends Param {
  public final String id_;
  public PId(String p1) { id_ = p1; }

  public <R,A> R accept(eyg.Absyn.Param.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof eyg.Absyn.PId) {
      eyg.Absyn.PId x = (eyg.Absyn.PId)o;
      return this.id_.equals(x.id_);
    }
    return false;
  }

  public int hashCode() {
    return this.id_.hashCode();
  }


}
