// File generated by the BNF Converter (bnfc 2.9.6).

package eyg.Absyn;

public abstract class RecordField implements java.io.Serializable {
  public abstract <R,A> R accept(RecordField.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(eyg.Absyn.RFKeyVal p, A arg);
    public R visit(eyg.Absyn.RFSpread p, A arg);

  }

}
